/**
 * Hand-verified native ranges for common food-forest / catalog species.
 * Keys: normalized scientific name (lowercase) or plant id.
 */
export const CURATED_NATIVE_ORIGIN_BY_SCIENTIFIC: Record<string, string> = {
  "pouteria caimito": "the Amazon basin and western South America",
  "pouteria campechiana": "southern Mexico and Central America",
  "malus domestica": "Central Asia (modern apples bred from wild apples in Kazakhstan)",
  "mangifera indica": "South Asia (India and Myanmar)",
  "persea americana": "southern Mexico and Guatemala",
  "carica papaya": "southern Mexico and Central America",
  "psidium guajava": "tropical Americas (Mexico through northern South America)",
  "annona squamosa": "tropical Americas and the West Indies",
  "annona muricata": "tropical Americas and the Caribbean",
  "annona glabra": "Florida wetlands and the Caribbean",
  "annona cherimola": "the Andes of South America",
  "annona reticulata": "tropical Americas and the Caribbean",
  "citrus × sinensis": "Southeast Asia (hybrid origin)",
  "citrus x sinensis": "Southeast Asia (hybrid origin)",
  "citrus × aurantium": "Southeast Asia",
  "citrus x aurantium": "Southeast Asia",
  "citrus × limon": "South Asia",
  "citrus x limon": "South Asia",
  "citrus × meyeri": "China (hybrid)",
  "citrus x meyeri": "China (hybrid)",
  "citrus reticulata": "East Asia",
  "citrus maxima": "Southeast Asia",
  "musa acuminata": "Southeast Asia and the Pacific",
  "musa × paradisiaca": "Southeast Asia (hybrid origin)",
  "musa x paradisiaca": "Southeast Asia (hybrid origin)",
  "artocarpus heterophyllus": "South and Southeast Asia",
  "artocarpus altilis": "New Guinea and Melanesia",
  "litchi chinensis": "southern China and Southeast Asia",
  "dimocarpus longan": "southern China and Southeast Asia",
  "nephelium lappaceum": "Southeast Asia",
  "averrhoa carambola": "Southeast Asia and the Malay Archipelago",
  "syzygium malaccense": "Malaysia and Indonesia",
  "punica granatum": "Iran and the Himalayas",
  "passiflora edulis": "southern Brazil, Paraguay, and Argentina",
  "hibiscus sabdariffa": "West Africa",
  "manihot esculenta": "South America (Amazon basin)",
  "ipomoea batatas": "tropical Americas",
  "cajanus cajan": "India",
  "moringa oleifera": "India and the foothills of the Himalayas",
  "cymbopogon citratus": "South and Southeast Asia",
  "zingiber officinale": "Southeast Asia",
  "curcuma longa": "South and Southeast Asia",
  "ocimum basilicum": "tropical Asia and Africa",
  "solanum lycopersicum": "western South America (Peru and Ecuador)",
  "capsicum annuum": "Mexico and Central America",
  "capsicum chinense": "the Amazon basin",
  "phaseolus vulgaris": "Mesoamerica",
  "cucurbita pepo": "Mexico and North America",
  "cucurbita moschata": "Central and northern South America",
  "cucurbita maxima": "South America",
  "sabal palmetto": "the southeastern United States (Florida and Gulf Coast)",
  "zamia integrifolia": "Florida and the coastal Southeast",
  "serenoa repens": "Florida and the southeastern United States",
  "callicarpa americana": "the southeastern United States",
  "hamelia patens": "Florida, the Caribbean, and Central America",
  "asimina triloba": "eastern North America",
  "diospyros virginiana": "eastern North America",
  "vaccinium corymbosum": "eastern North America",
  "rubus idaeus": "Europe and western Asia",
  "fragaria × ananassa": "hybrid origin (North and South America)",
  "fragaria x ananassa": "hybrid origin (North and South America)",
  "cocos nucifera": "Indo-Pacific coasts and islands",
  "phoenix dactylifera": "North Africa and the Middle East",
  "eugenia uniflora": "Brazil, Uruguay, and Paraguay",
  "eugenia brasiliensis": "southern Brazil",
  "plinia cauliflora": "southern Brazil",
  "borassus flabellifer": "South and Southeast Asia",
  "cananga odorata": "tropical Asia and the Pacific",
  "pimenta dioica": "Central America and the Caribbean",
  "myrciaria cauliflora": "southern Brazil",
  "theobroma cacao": "the Amazon basin of South America",
  "coffea arabica": "Ethiopia and the Arabian Peninsula",
  "allamanda cathartica": "tropical America and the West Indies",
  "aloe vera": "the Arabian Peninsula",
};

export const CURATED_NATIVE_ORIGIN_BY_ID: Record<string, string> = {
  abiu: "the Amazon basin and western South America",
  "apple-anna": "Central Asia (modern apples bred from wild apples in Kazakhstan)",
  mango: "South Asia (India and Myanmar)",
  papaya: "southern Mexico and Central America",
  avocado: "southern Mexico and Guatemala",
  guava: "tropical Americas (Mexico through northern South America)",
  coontie: "Florida and the coastal Southeast",
  "saw-palmetto": "Florida and the southeastern United States",
  beautyberry: "the southeastern United States",
  firebush: "Florida, the Caribbean, and Central America",
};
